[Variables]

A			="M-1"
ATUT		="M-1#CRLF#Tutorial"
B			="ENG"
C			="CHEM"
D			="BEEE"
E			="EG"
F			="MP"
G 			="PROGRA-#CRLF#-MMING"
brek		="Lunch"
S			="CHEM/B3E Lab#CRLF#Lab"
T			="EG#CRLF#Lab"
U 			="ENG#CRLF#Lab"
V 			="MP#CRLF#Lab"
W 			="M/L"
X 			="DM"
Y 			="RO"
Z 			="PROJEC-#CRLF#-CT"
SBS			="SBSI/#CRLF#UBA/RO"

AColor		=255,139,148
BColor		=255,179,186
CColor		=255,223,186
DColor		=255,255,186
brekColor	=220,237,193
EColor		=168,230,207
FColor		=186,225,255
GColor		=238,203,255
SColor		=238,203,255
TColor		=254,255,163
UColor 		=173,178,251
VColor		=192,244,184
WColor		=186,225,255
XColor		=168,230,207
YColor 		=220,237,193
ZColor		=238,203,255

white		=255,255,255
grey		=97,97,97
grey1		=0,0,0,150
grey2		=0,0,0,100

//////////////////////////////////////////////////////////////

;MONDAY
;----------------------
Monday			=#S#
Monday2			=#S#
Monday3			=#E#
Monday4			=#SBS#
Monday5			=#brek#
Monday6			=#C#
Monday7 		=#U#
Monday8 		=#U#

MondayColor			=#AColor#
MondayColor2		=#BColor#
MondayColor3		=#SColor#
MondayColor4		=#SColor#
MondayColor5		=#brekColor#
MondayColor6		=#EColor#
MondayColor7		=#DColor#
MondayColor8		=#CColor#

;TUESDAY
;----------------------
Tuesday			=#E#
Tuesday2		=#D#
Tuesday3		=#A#
Tuesday4		=#ATUT#
Tuesday5		=#brek#
Tuesday6		=#C#
Tuesday7		=#W#
Tuesday8		=#B#

TuesdayColor		=#BColor#
TuesdayColor2		=#WColor#
TuesdayColor3		=#EColor#
TuesdayColor4		=#CColor#
TuesdayColor5		=#brekColor#
TuesdayColor6		=#DColor#
TuesdayColor5		=#XColor#
TuesdayColor6		=#YColor#


;WEDNESDAY
;----------------------
Wednesday		=#B#
Wednesday2		=#T#
Wednesday3		=#T#
Wednesday4		=#T#
Wednesday5		=#brek#
Wednesday6		=#D#
Wednesday7 		=#D#
Wednesday8 		=#C#

WednesdayColor		=#CColor#
WednesdayColor2		=#DColor#
WednesdayColor3		=#BColor#
WednesdayColor4		=#AColor#
WednesdayColor5		=#brekColor#
WednesdayColor6		=#TColor#
WednesdayColor7 	=#TColor#
WednesdayColor8 	=#TColor#

;THURSDAY
;----------------------
Thursday		=#S#
Thursday2		=#S#
Thursday3		=#B#
Thursday4		=#A#
Thursday5		=#brek#
Thursday6		=#C#
Thursday7		=#C#
Thursday8		=#D#

ThursdayColor		=#GColor#
ThursdayColor2		=#ZColor#
ThursdayColor3		=#BColor#
ThursdayColor4		=#EColor#
ThursdayColor5		=#brekColor#
ThursdayColor6		=#CColor#
ThursdayColor7		=#SColor#
ThursdayColor8		=#SColor#

;FRIDAY
;----------------------
Friday			=#D#
Friday2			=#A#
Friday3			=#E#
Friday4			=#E#
Friday5			=#brek#
Friday6			=#B#
Friday7			=#V#
Friday8			=#V#

FridayColor 		=#CColor#
FridayColor2		=#VColor#
FridayColor3		=#VColor#
FridayColor4		=#VColor#
FridayColor5		=#brekColor#
FridayColor6		=#AColor#
FridayColor7		=#DColor#
FridayColor8		=#EColor#

;SATURDAY
;----------------------
Saturday			="nothing   w"
Saturday2			="to do    w"
Saturday3			="take"
Saturday4			="a"
Saturday5			="good"
Saturday6			="break"
Saturday7			="today"
Saturday8			=":3"


SaturdayColor		=#EColor#
SaturdayColor2		=#DColor#
SaturdayColor3		=#AColor#
SaturdayColor4		=#GColor#
SaturdayColor5		=#brekColor#
SaturdayColor6		=#CColor#
SaturdayColor7		=#UColor#
SaturdayColor8		=#UColor#


;Sunday
;----------------------
Sunday			="nothing   w"
Sunday2			="to do    w"
Sunday3			="take"
Sunday4			="a"
Sunday5			="good"
Sunday6			="break"
Sunday7			="today"
Sunday8			=":3"


SundayColor			=#brekColor#
SundayColor2		=#brekColor#
SundayColor3		=#brekColor#
SundayColor4		=#brekColor#
SundayColor5		=#brekColor#
SundayColor6		=#brekColor#
SundayColor7		=#brekColor#
SundayColor8		=#brekColor#

//////////////////////////////////////////////////////////////

;TIME [Mon,Tue,Wed,Thu,Fri,Sat]
;----------------------
t1		=9:00
t2		=9:45
t3		=10:30
t4		=11:20
t5		=12:10
t6		=1:00
t7		=1:50
t8		=2:40
t9		=3:30


